# Generated by Django 3.1.1 on 2020-09-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Mathlete 1', max_length=100),
            preserve_default=False,
        ),
    ]
