# Generated by Django 3.1.1 on 2020-09-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='members',
            new_name='mathletes',
        ),
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='Problem 1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_text',
            field=models.CharField(default='What is 1+1?', max_length=1000),
            preserve_default=False,
        ),
    ]
