# Generated by Django 3.1.1 on 2020-09-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200913_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
