# Generated by Django 3.1.1 on 2020-09-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200922_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='grader_data',
            field=models.JSONField(blank=True, help_text="Data for the problem's grader to use. The format depends on the type of grader", null=True),
        ),
    ]
