# Generated by Django 3.1.1 on 2020-09-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200926_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submit_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
