# Generated by Django 3.1.1 on 2020-09-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200926_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ML', 'Contestant'), ('ST', 'CMU Student')], default='ML', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='full name', max_length=100),
        ),
    ]
