# Generated by Django 3.1.1 on 2020-09-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200927_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
    ]
