# Generated by Django 3.1.1 on 2020-10-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200927_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_number',
            field=models.CharField(default=1, help_text='For most exams,             problems are numbered 1, 2, 3, ..., but for the optimization round,             they are numbered 1a, 1b, 1c, 2a, 2b, ... (each problem has multiple test cases', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('exam', 'problem_number')},
        ),
    ]
