# Generated by Django 3.1.2 on 2020-10-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20201004_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='teamname', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ML', 'Contestant'), ('ST', 'CMU Student'), ('CO', 'Coach')], default='ML', max_length=2),
        ),
    ]
