# Generated by Django 3.1.2 on 2020-10-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20201031_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
