# Generated by Django 3.1.2 on 2020-11-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20201107_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
