# Generated by Django 3.1.3 on 2020-12-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20201109_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='form',
            field=models.CharField(choices=[('OPT', 'Optimization'), ('AI', 'AI'), ('MATH', 'Math (short answer)'), ('POW', 'Power (proof)')], default='OPT', max_length=4),
        ),
    ]
