# Generated by Django 3.1.3 on 2020-12-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20201109_0403'),
        ('website', '0019_snippet'),
    ]

    operations = [
    ]
