# Generated by Django 3.1.3 on 2020-12-06 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_exam_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='num_cases',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_case',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
