# Generated by Django 3.1.3 on 2020-12-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20201206_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='grader_data',
        ),
        migrations.AddField(
            model_name='score',
            name='opt_cases',
            field=models.JSONField(blank=True, default=list, help_text='List of             best score for each case of an optimization round problem', null=True),
        ),
    ]
