# Generated by Django 3.1.3 on 2020-12-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20201206_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_text',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='score',
            name='opt_cases',
            field=models.JSONField(blank=True, default=list, help_text='List of             best scores for each case of an optimization round problem', null=True),
        ),
    ]
