# Generated by Django 3.1.3 on 2020-12-07 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20201206_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='num_cases',
            new_name='num_tasks',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='test_case',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='score',
            name='opt_cases',
        ),
        migrations.AddField(
            model_name='score',
            name='task_scores',
            field=models.JSONField(blank=True, default=list, help_text='List of             best scores for each task of an optimization round problem', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
