# Generated by Django 3.1.3 on 2020-12-07 08:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20201206_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pdf_link',
            field=models.CharField(default='https://www.google.com/', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('input_link', models.CharField(max_length=1000)),
                ('grader_data', models.JSONField(blank=True, help_text="Data for the             problem's grader to use. The format depends on the type of grader", null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='website.problem')),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='website.task'),
        ),
    ]
