# Generated by Django 3.1.3 on 2020-12-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20201207_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pdf_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
