# Generated by Django 3.1.4 on 2020-12-23 00:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_problem_markdown_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='rich_text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
