# Generated by Django 3.1.4 on 2020-12-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_problem_rich_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='markdown_text',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_text',
        ),
    ]
