# Generated by Django 3.1.4 on 2020-12-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20201224_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='rich_text',
            new_name='problem_text',
        ),
    ]
