# Generated by Django 3.1.4 on 2020-12-27 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20201225_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='num_tasks',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
