# Generated by Django 3.1.4 on 2020-12-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_auto_20201227_1425'),
        ('website', '0025_merge_20201205_1648'),
        ('website', '0025_merge_20201205_1655'),
    ]

    operations = [
    ]
