# Generated by Django 3.1.5 on 2021-01-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20210101_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='is_registered',
            new_name='is_finalized',
        ),
    ]
