# Generated by Django 3.1.5 on 2021-01-15 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20210101_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('history', models.JSONField()),
                ('time', models.TimeField()),
                ('numplayers', models.IntegerField()),
            ],
            options={
                'db_table': 'games_airound',
            },
        ),
        migrations.CreateModel(
            name='AIGrader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField()),
                ('currently', models.TextField()),
            ],
            options={
                'db_table': 'graders_airound',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AISubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('code', models.TextField()),
                ('score', models.FloatField()),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.competitor')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.aigame')),
            ],
            options={
                'db_table': 'submissions_airound',
            },
        ),
        migrations.CreateModel(
            name='AIProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.problem')),
            ],
            options={
                'db_table': 'contests_airound',
            },
        ),
        migrations.AddField(
            model_name='aigame',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.aiproblem'),
        ),
        migrations.AddField(
            model_name='aigame',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.aigrader'),
        ),
    ]
