# Generated by Django 3.1.5 on 2021-01-15 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_taskscore'),
        ('website', '0048_auto_20210114_2043'),
    ]

    operations = [
    ]
