# Generated by Django 3.1.5 on 2021-01-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_auto_20210115_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='reg_start_date',
        ),
        migrations.AddField(
            model_name='contest',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tester',
            field=models.BooleanField(default=False, help_text='whether they can view private contests'),
        ),
    ]
