# Generated by Django 3.1.5 on 2021-01-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_auto_20210116_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grader_data_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
