# Generated by Django 3.1.5 on 2021-01-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_auto_20210114_2228'),
        ('website', '0054_task_grader_data_file'),
    ]

    operations = [
    ]
