# Generated by Django 3.1.5 on 2021-01-20 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_merge_20210119_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='numplayers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aiproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiproblem', to='website.problem'),
        ),
        migrations.AlterField(
            model_name='aisubmission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
