# Generated by Django 3.1.5 on 2021-01-23 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_auto_20210119_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aigame',
            old_name='problem',
            new_name='aiproblem',
        ),
        migrations.AddField(
            model_name='aigame',
            name='miniround',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aisubmission',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisubmissions', to='website.aigame'),
        ),
    ]
