# Generated by Django 3.1.5 on 2021-01-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_auto_20210122_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='miniround_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
