# Generated by Django 3.1.5 on 2021-01-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_exam_miniround_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniRoundScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miniround', models.IntegerField()),
                ('points', models.FloatField(default=0.0)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniroundscores', to='website.score')),
            ],
        ),
    ]
