# Generated by Django 3.1.5 on 2021-01-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_miniroundscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigame',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='grader_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
