# Generated by Django 3.1.5 on 2021-01-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_auto_20210123_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='error_msg',
            field=models.TextField(blank=True),
        ),
    ]
