# Generated by Django 3.1.5 on 2021-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_submission_error_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskscore',
            name='norm_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskscore',
            name='raw_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
