# Generated by Django 3.1.5 on 2021-01-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_auto_20210124_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='best_raw_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
