# Generated by Django 3.1.5 on 2021-01-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_auto_20210124_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskscore',
            name='norm_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=40),
        ),
    ]
