# Generated by Django 3.1.5 on 2021-01-25 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_auto_20210124_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='reg_end_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_finalized',
        ),
        migrations.AddField(
            model_name='contest',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='reg_deadline',
            field=models.DateField(default=datetime.date(2021, 1, 25)),
            preserve_default=False,
        ),
    ]
