# Generated by Django 3.1.5 on 2021-01-27 03:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_auto_20210125_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigame',
            name='test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='miniround_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 3, 41, 58, 882637, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='taskscore',
            unique_together={('task', 'score')},
        ),
    ]
