# Generated by Django 3.1.5 on 2021-01-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_auto_20210127_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigame',
            name='test',
        ),
        migrations.AddField(
            model_name='aiproblem',
            name='starter_file',
            field=models.TextField(blank=True),
        ),
    ]
