# Generated by Django 3.1.5 on 2021-01-28 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_auto_20210127_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigame',
            name='aiproblem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aigames', to='website.aiproblem'),
        ),
    ]
