# Generated by Django 3.1.5 on 2021-01-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_auto_20210127_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='visualizer',
            field=models.TextField(blank=True),
        ),
    ]
