# Generated by Django 3.1.5 on 2021-01-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0071_aiproblem_visualizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='display_miniround',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miniroundscore',
            name='games',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='miniroundscore',
            name='norm_w_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='miniroundscore',
            name='weighted_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='MiniRoundTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miniround', models.IntegerField()),
                ('total_score', models.FloatField(default=0.0)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniroundtotals', to='website.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='MiniRoundQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miniround', models.IntegerField()),
                ('num_games', models.IntegerField(default=-1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniroundqueues', to='website.exam')),
            ],
        ),
    ]
