# Generated by Django 3.1.5 on 2021-01-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_auto_20210129_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='num_grace_minirounds',
            field=models.IntegerField(default=0),
        ),
    ]
