# Generated by Django 3.1.5 on 2021-01-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_auto_20210131_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_graded',
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='website.task'),
        ),
    ]
