# Generated by Django 3.1.5 on 2021-02-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_auto_20210131_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='grader_filename',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
