# Generated by Django 3.1.5 on 2021-02-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0076_problem_grader_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='raw_grader_data',
            field=models.TextField(blank=True),
        ),
    ]
