# Generated by Django 3.1.5 on 2021-02-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0077_task_raw_grader_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='taskscore',
            name='raw_points',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
