# Generated by Django 3.1.6 on 2021-02-05 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0078_auto_20210201_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisubmission',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aisubmissions', to='website.submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='sigma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aigame',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
