# Generated by Django 3.1.6 on 2021-02-05 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_auto_20210204_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_played', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prev_rating', models.FloatField(default=0)),
                ('new_rating', models.FloatField(default=0)),
                ('aisubmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchresults', to='website.aisubmission')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchresults', to='website.score')),
            ],
        ),
    ]
