# Generated by Django 3.1.6 on 2021-02-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigame',
            name='burst_matches',
            field=models.IntegerField(default=10),
        ),
    ]
