# Generated by Django 3.1.6 on 2021-02-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_aigame_burst_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigame',
            name='burst_matches',
        ),
        migrations.AddField(
            model_name='aiproblem',
            name='burst_matches',
            field=models.IntegerField(default=10),
        ),
    ]
