# Generated by Django 3.1.6 on 2021-02-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0082_auto_20210205_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisubmission',
            name='code',
        ),
    ]
