# Generated by Django 3.1.6 on 2021-02-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0084_auto_20210215_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='division',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
