# Generated by Django 3.1.6 on 2021-02-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0085_auto_20210215_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.IntegerField(blank=True, null=True)),
                ('exampair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divchoices', to='website.exampair')),
                ('mathlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divchoices', to='website.mathlete')),
            ],
        ),
    ]
