# Generated by Django 3.1.6 on 2021-02-23 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0087_team_wants_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='date',
            field=models.DateField(default=datetime.date(2021, 2, 23)),
            preserve_default=False,
        ),
    ]
