# Generated by Django 3.1.6 on 2021-02-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0089_score_latest_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
