# Generated by Django 3.1.6 on 2021-02-26 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0093_contest_show_final_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='date',
        ),
    ]
