# Generated by Django 3.1.7 on 2021-02-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0094_remove_contest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
