# Generated by Django 3.1.7 on 2021-03-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0097_contest_div_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
