# Generated by Django 3.1.7 on 2021-03-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0099_exam_show_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndivSweepstake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0.0)),
                ('mathlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indivsweepstakes', to='website.mathlete')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indivsweepstakes', to='website.team')),
            ],
        ),
    ]
