# Generated by Django 3.1.7 on 2021-03-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0100_indivsweepstake'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='show_sweepstakes',
            field=models.BooleanField(default=False, help_text='make final results public'),
        ),
    ]
