# Generated by Django 3.1.7 on 2021-03-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0101_contest_show_sweepstakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indivsweepstake',
            name='total_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.CreateModel(
            name='Sweepstake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indiv_total', models.FloatField(db_index=True, default=0.0)),
                ('norm_power', models.FloatField(default=0.0)),
                ('norm_team', models.FloatField(default=0.0)),
                ('norm_indiv', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(db_index=True, default=0.0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sweepstake', to='website.team')),
            ],
        ),
    ]
