# Generated by Django 3.1.7 on 2021-03-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0102_auto_20210312_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_math',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
